name: 'Test artifacts'

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Test creating dist files
        run: dd if=/dev/zero of=test.dat  bs=1024  count=1024
      - name: 'Upload artifact'
        uses: 'actions/upload-artifact@v4'
        with:
          path: test.dat
